name: Build and Compile

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # You can change the runner environment if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Choose the appropriate Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  # Adjust the build command as needed
