name: Build and Compile

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run : npm install -g pnpm  
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v3
        with:
           name: compiled-package
           path: dist/blitz-adblock.zip
